### ISSUE TITLE
Image title text ignored

### ISSUE THREAD

**Issue by keawade** [gitterHQ/gitter-markdown-processor#8]
Per the [Markdown syntax for images](https://daringfireball.net/projects/markdown/syntax#img), an optional title attribute can be provided following the url in single or double quotes. Example: `![Alt text](/path/to/img.jpg "Optional title")`

The processor seems to be taking the url, alt text, and a title as arguments but [the title arg is unused](https://github.com/gitterHQ/gitter-markdown-processor/blob/78a00600aef9642fb2154e1843fb175e780162d1/lib/process-chat.js#L190-L195).

Is there a reason for this?

**Comment by MadLittleMods** [comment]
I don't think there is a reason. PR welcome 😀
